apiVersion: v1
kind: Plugin
metadata:
  author: sheetung
  name: ChatQuizforLangBot
  repository: 'https://github.com/sheetung/ChatQuizforLangBot'
  version: 0.0.3
  description:
    en_US: 'Conversational quiz plugin for LangBot'
    zh_Hans: 'LangBot 对话式测验插件'
  label:
    en_US: ChatQuizforLangBot
    zh_Hans: 有趣的测试
  icon: assets/icon.png  # replace in assets/icon.svg
spec:
  config: []
  components:
    EventListener:
      fromDirs:
        - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: ChatQuizLB
